config/routes.rb
Guildfordoffers::Application.routes.draw do
  resources :emails
  resources :posts
  resources :users
  resources :user_sessions
  match 'feed' => "posts#feed", :as => :feed, :defaults => {:format => 'rss'}
  match 'postlist' => "posts#list", :as => :postlist
  match 'search' => "posts#search", :as => :search
  match 'about' => "pages#about"
  match 'contact' => "pages#contact"
  match 'faq' => "pages#faq"
  match 'partners' => "pages#partners"
  match 'error404' => "errors#404"
  match 'error422' => "errors#422"
  match 'error500' => "errors#500"
  match 'controlpanel' => "pages#controlpanel", :as => :control
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '*a', :to => "errors#error404"

  root :to => "posts#index"











end

app/views/pages/about.html.erb
<div id="notice"><%= notice %></div>

<h1>  About Page </h1>

<h2>Our Goal</h2>
<p class="about">
Hello! So what is Guildford Student Offers all about? Well its pretty simple.
We go and out find the deals so you don’t have to!
And when we have found them, we share them here and on our Facebook page so you can hear about them, and most importantly use them!
<br/><br/>
Browse, select, print, or share to your facebook wall. And you can take the deals anywhere!
<br/><br/>
The more people that connect with us via social networks from "liking" our facebook page, to spreading the news on twitter allows us to get better deals and offers for you!!
<br/><br/>
Thanks
<br/><br/>
Guildford Student Offers!
</p>

<h2>Offers On The Go</h2>
<p class="about">
Watch this space for news on our expansion into new media.
<br/>
We want to be able to provide you with the means to have access to these great offers on the go via your mobile devices with simple money saving apps.
</p>

app/views/pages/contact.html.erb
<div id="notice"><%= notice %></div>

<h1>Contact Us</h1>
<h2>We would love to hear what you have to say.</h2>
<div class="contactusleft">
  <h3>Where we live.</h3>
  <p>
    We live with the very lovely folks at SETSquared, within The Surrey Technology Centre, close to Guildford City Centre and the University of Surrey. If you would like to talk to us, there are many ways you can keep in touch.
  </p>
  <h3>Address</h3>
  <p>
    Guildford Student Offers.<br/>
    iGeolise Ltd.<br/>
    Surrey Technology Centre,<br/>
    40 Occam Road,<br/>
    Guildford,<br/>
    Surrey,<br/>
    GU2 7YG.<br/>
    United Kingdom.<br/>
  </p>
  <p>
    <b>Phone:</b> +44 (0)1483 688081<br/>
    <b>Email:</b> info@guildfordoffers.com<br/>
  </p>
  <h3>Social Networks</h3>
  <p>
    <a href="http://www.facebook.com/guildfordoffers">&#187;Facebook</a><br/>
    <a href="http://twitter.com/guildfordoffers">&#187;Twitter</a><br/>
    <a href="http://www.guildfordoffers.com">&#187;LinkedIn</a><br/>
  </p>
</div>
<div class="contactusright">
  <h3>Where we are on the map</h3>
  <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=40+Occam+Road,+Guildford+GU2+7YG&amp;aq=&amp;sll=51.240256,-0.612634&amp;sspn=0.012346,0.032959&amp;g=40+Occam+Road,+Guildford+GU2+7YG&amp;ie=UTF8&amp;hq=&amp;hnear=40+Occam+Rd,+Guildford+GU2+7,+United+Kingdom&amp;t=h&amp;ll=51.245208,-0.611801&amp;spn=0.018805,0.036478&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br />
  <a href="http://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=40+Occam+Road,+Guildford+GU2+7YG&amp;aq=&amp;sll=51.240256,-0.612634&amp;sspn=0.012346,0.032959&amp;g=40+Occam+Road,+Guildford+GU2+7YG&amp;ie=UTF8&amp;hq=&amp;hnear=40+Occam+Rd,+Guildford+GU2+7,+United+Kingdom&amp;t=h&amp;ll=51.245208,-0.611801&amp;spn=0.018805,0.036478&amp;z=14&amp;iwloc=A">View Larger Map</a>
</div>

app/views/pages/controlpanel.html.erb
<div id="notice"><%= notice %></div>

<h1> Control Panel </h1>

<%= link_to "Mailing List", emails_path%> <br/>
<%= link_to "Add Email To Mailing List", new_email_path%> <br/>

<%= link_to "Offers List (Table View)", :postlist %> <br/>
<%= link_to "Offers List (Normal)", posts_path%> <br/>
<%= link_to "Post New Offer", new_post_path%> <br/>

<%= link_to "User Logins", users_path%> <br/>
<%= link_to "Create New User", new_user_path%> <br/>

<h2>Internal Navigation Links</h2>
<%= link_to "Home", root_url%><br/>
<%= link_to "Control Panel", :control%><br/>
<%= link_to "Login", :login %><br/>
<%= link_to "Logout", :logout%><br/>
<a href="/partners">Want To Advertise Here?</a><br/>
<a href="/faq">FAQ</a><br/>
<a href="/contact">Contact</a><br/>
<a href="/about">About</a><br/>
<a href="/error404">404 error page</a><br/>
<a href="/error422">422 error page</a><br/>
<a href="/error500">500 error page</a><br/>

<h2>External Navigation Links</h2>
<a href="http://www.facebook.com/guildfordoffers">Facebook Page</a><br/>
<a href="http://twitter.com/guildfordoffers">Twitter Page</a><br/>
<a href="http://www.igeolise.com">iGeolise</a><br/>

app/views/pages/faq.html.erb
<div id="notice"><%= notice %></div>

<h1>FAQ</h1>

<h2 class="faq">How was this site created?</h2>
<p class="faq">
  This site was initially based upon word press in its early days. An image of what the site was can seen <a href="/images/oldwordpresssite.JPG">here</a>.
  In late 2010 development of the current site took place as a joint project between iGeolise and Stephen Law a final year computing student at the University Of Surrey. It was built in Ruby On Rails 3 to achieve the features that you see today.
</p>

<h2 class="faq">How can i suggest an offer?</h2>
<p class="faq">
  If you wish to tell us about a specific offer or you would like to see offers from a certain company just send us a message via any of the methods <a href="/contact">here</a>.
</p>

<h2 class="faq">How does "liking", "tweeting", "sharing" etc help get better offers?</h2>
<p class="faq">
  The more people that are seen to be connected to this site allows us to easily approach new or old companies to ask them for offers for you as it shows them that you guys are here ready to try their products and all they need is to show you they exists by putting themselves here.
</p>

<h2 class="faq">I own a business how can I promote my offer here?</h2>
<p class="faq">
  If you represent a business that would like to promote an offer here then we would love to hear form you! Find more information about our business partnerships <a href="/partners">here</a>. Then contact us via the details <a href="/contact">here</a>.
</p>

<h2 class="faq">What is a RSS feed?</h2>
<p class="faq">
  An RSS (Rich Site Summary) feed is an XML format that allows for other websites or readers to be able to easily get the latest updates from the site automatically without having to manually visit.
</p>
